### ISSUE TITLE
 RamsesClimateEntityDescription.__init__() missing 1 required keyword-only argument: 'extra_attributes'

### ISSUE THREAD

**Issue by zxdavb** [zxdavb/ramses_cc#119]
@trvrnrth 

This is what I'm seeing:
```python
2023-12-22 22:44:30.777 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.ramses_cc.binary_sensor
Traceback (most recent call last):
  File "/home/dbonnes/clients/hass/homeassistant/loader.py", line 834, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dbonnes/clients/hass/homeassistant/loader.py", line 851, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/dbonnes/clients/ramses_cc/custom_components/ramses_cc/binary_sensor.py", line 210, in <module>
    RamsesBinarySensorEntityDescription(
TypeError: RamsesBinarySensorEntityDescription.__init__() missing 1 required keyword-only argument: 'extra_attributes'

2023-12-22 22:44:30.781 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform 'ramses_cc.binary_sensor': Platform not found (Exception importing custom_components.ramses_cc.binary_sensor).

2023-12-22 22:44:30.852 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up ramses_cc platform for sensor
Traceback (most recent call last):
  File "/home/dbonnes/clients/hass/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/home/dbonnes/clients/ramses_cc/custom_components/ramses_cc/sensor.py", line 161, in async_setup_platform
    RamsesSensorEntityDescription(
TypeError: RamsesSensorEntityDescription.__init__() missing 1 required keyword-only argument: 'extra_attributes'

2023-12-22 22:44:30.873 ERROR (MainThread) [homeassistant.components.climate] Error while setting up ramses_cc platform for climate
Traceback (most recent call last):
  File "/home/dbonnes/clients/hass/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/home/dbonnes/clients/ramses_cc/custom_components/ramses_cc/climate.py", line 285, in async_setup_platform
    RamsesClimateEntityDescription(
TypeError: RamsesClimateEntityDescription.__init__() missing 1 required keyword-only argument: 'extra_attributes'
...
```

**Comment by zxdavb** [comment]
I have pulled `sensor_types` out as `SENSOR_TYPES` (could be called `BINARY_SENSOR_TYPES`).

**Comment by zxdavb** [comment]
> `required keyword-only argument`

Should be optional?

**Comment by zxdavb** [comment]
```python
2023-12-22 22:55:11.489 ERROR (MainThread) [homeassistant.util.logging] Exception in async_write_ha_state when dispatching 'ramses_cc_update': ()
Traceback (most recent call last):
  File "/home/dbonnes/clients/hass/homeassistant/helpers/entity.py", line 754, in async_write_ha_state
    self._async_write_ha_state()
  File "/home/dbonnes/clients/hass/homeassistant/helpers/entity.py", line 875, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dbonnes/clients/hass/homeassistant/helpers/entity.py", line 815, in __async_calculate_state
    attr.update(self.extra_state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dbonnes/clients/ramses_cc/custom_components/ramses_cc/__init__.py", line 205, in extra_state_attributes
    for k, v in self.entity_description.extra_attributes.items()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'items'

2023-12-22 22:55:11.498 ERROR (MainThread) [homeassistant.util.logging] Exception in async_write_ha_state when dispatching 'ramses_cc_update': ()
Traceback (most recent call last):
  File "/home/dbonnes/clients/hass/homeassistant/helpers/entity.py", line 754, in async_write_ha_state
    self._async_write_ha_state()
  File "/home/dbonnes/clients/hass/homeassistant/helpers/entity.py", line 875, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dbonnes/clients/hass/homeassistant/helpers/entity.py", line 815, in __async_calculate_state
    attr.update(self.extra_state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dbonnes/clients/ramses_cc/custom_components/ramses_cc/__init__.py", line 205, in extra_state_attributes
    for k, v in self.entity_description.extra_attributes.items()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'items'

2023-12-22 22:55:11.506 ERROR (MainThread) [homeassistant.util.logging] Exception in async_write_ha_state when dispatching 'ramses_cc_update': ()
Traceback (most recent call last):
  File "/home/dbonnes/clients/hass/homeassistant/helpers/entity.py", line 754, in async_write_ha_state
    self._async_write_ha_state()
  File "/home/dbonnes/clients/hass/homeassistant/helpers/entity.py", line 875, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dbonnes/clients/hass/homeassistant/helpers/entity.py", line 815, in __async_calculate_state
    attr.update(self.extra_state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dbonnes/clients/ramses_cc/custom_components/ramses_cc/__init__.py", line 205, in extra_state_attributes
    for k, v in self.entity_description.extra_attributes.items()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'items'
```

**Comment by zxdavb** [comment]
I am not familiar with this:
```python
@dataclass(kw_only=True)
class RamsesEntityDescription(EntityDescription):
    """Class describing Ramses entities."""

    has_entity_name: bool = True
    extra_attributes: list[str] = field(default_factory=list)
```

**Comment by trvrnrth** [comment]
Odd. It works fine for me. These are [the docs](https://docs.python.org/3/library/dataclasses.html#default-factory-functions) for creating a new list for the dataclass. It's a list, not a dict as it is a list of device properties to expose as attributes.

**Comment by zxdavb** [comment]
But:
```python
    RamsesBinarySensorEntityDescription(
        key="active_fault",
        name="Active fault",
        rf_class=Logbook,
        entity_class=RamsesLogbookBinarySensor,
        device_class=BinarySensorDeviceClass.PROBLEM,
        extra_attributes={  # this is a dict
            ATTR_ACTIVE_FAULT: "active_fault",
            ATTR_LATEST_EVENT: "latest_event",
            ATTR_LATEST_FAULT: "latest_fault",
        },
```

**Comment by trvrnrth** [comment]
🤦  Yes, you're absolutely correct. The default should be a dict (type `dict[str, str]`)! I initially implemented it as a list before changing it to be more flexible but was completely forgetting about that when writing that comment.

**Comment by zxdavb** [comment]
...but doesn't solve my problem.

**Comment by trvrnrth** [comment]
We don't actually need it to default to an empty dict. I'm confused as to why that's not working for you but does the following work instead?
```
    extra_attributes: dict[str, str] | None = None
```

**Comment by zxdavb** [comment]
Well.

I had tried
```python
extra_attributes: dict[str, str] | None = field(default_factory=dict)
```
... which didn't work, but your suggestion does!

**Comment by zxdavb** [comment]
I'll push that.

**Comment by zxdavb** [comment]
We're both running **dev** branch of HA, with Python 3.11.6, right?

**Comment by trvrnrth** [comment]
> We're both running **dev** branch of HA, with Python 3.11.6, right?

I've been running on a slightly out of date dev branch of HA (Dec 3) running with the provided devcontainer which has Python 3.11.4. I also tested on my main install of 2023.12.3. I'll update to latest dev for good measure.
