### ISSUE TITLE
'RemoteEntityDescription' object has no attribute 'extra_attributes'

### ISSUE THREAD

**Issue by zxdavb** [zxdavb/ramses_cc#124]
@trvrnrth 

```python
2023-12-24 13:17:11.918 ERROR (MainThread) [homeassistant.components.remote] Error adding entities for domain remote with platform ramses_cc
Traceback (most recent call last):
  File "/home/dbonnes/clients/hass/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/home/dbonnes/clients/hass/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/home/dbonnes/clients/hass/homeassistant/helpers/entity.py", line 1091, in add_to_platform_finish
    self.async_write_ha_state()
  File "/home/dbonnes/clients/hass/homeassistant/helpers/entity.py", line 754, in async_write_ha_state
    self._async_write_ha_state()
  File "/home/dbonnes/clients/hass/homeassistant/helpers/entity.py", line 875, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dbonnes/clients/hass/homeassistant/helpers/entity.py", line 815, in __async_calculate_state
    attr.update(self.extra_state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dbonnes/clients/ramses_cc/custom_components/ramses_cc/remote.py", line 136, in extra_state_attributes
    return super().extra_state_attributes | {"commands": self._commands}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dbonnes/clients/ramses_cc/custom_components/ramses_cc/__init__.py", line 202, in extra_state_attributes
    if self.entity_description.extra_attributes:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RemoteEntityDescription' object has no attribute 'extra_attributes'
```

**Comment by zxdavb** [comment]
I suspect you don't have any HVAC, only Heat (CH/DHW), so you wouldn' have seen this in testing.

I think you can invoke this error if you add this to your **configuration.yaml**:
```yaml
ramses_cc:

  orphans_hvac: [20:123456]  # instantiate this device
  
  known_list: 
    20:123456: {class: REM}  # it is a remote
```

**Comment by trvrnrth** [comment]
I'm away from my dev environment for a while so can't test but  #125 should fix that.
