### ISSUE TITLE
Assertion failure due to hold_secs arg

### ISSUE THREAD

**Issue by maleadt** [zxdavb/ramses_cc#146]
Overnight, presumably after the update to 0.31.x, I've started seeing the following errors whenever I do a `send_command` service call:

```
ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall fan.set_preset_mode (c:01HMX5TFGEBKD9RYSS38YH3N9F): entity_id=['fan.orcon_hrc_350'], preset_mode=medium>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 2165, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 2186, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 882, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 952, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 285, in async_handle_set_preset_mode_service
    await self.async_set_preset_mode(preset_mode)
  File "/usr/src/homeassistant/homeassistant/components/template/fan.py", line 288, in async_set_preset_mode
    await self.async_run_script(
  File "/usr/src/homeassistant/homeassistant/components/template/template_entity.py", line 557, in async_run_script
    await script.async_run(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1587, in async_run
    return await asyncio.shield(run.async_run())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 426, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 479, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 502, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 476, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 713, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 675, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2149, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2186, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 882, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 952, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/ramses_cc/remote.py", line 212, in async_send_command
    assert not kwargs, kwargs  # TODO: remove me
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: {'hold_secs': 0.0}
```

Using Home Assistant 2024.1.5. I didn't see anything in the release notes about changes to `send_command`, so opening an issue. The service invocation is simple and doesn't specify `hold_secs`:

```
  - service: remote.send_command
    data:
      entity_id: remote.29_150155
      command: refresh
```

**Comment by zxdavb** [comment]
I have dixed this bug in #44d3294 (and #6d0861c).

In the meantime (and for ongoing), use the `ramses_cc.send_command` service call.
