### ISSUE TITLE
Send command: Failed to perform the action climate/set_hvac_mode. unknown error

### ISSUE THREAD

**Issue by shagadeli** [zxdavb/ramses_cc#210]
I've a Siber DF Evo 4 with a physical remote control and the ESP32 Ramses board from Indalo-Tech. I can see every available sensor value and I get 3 devices on the integration, the Gateway, the remote and a FAN device. 
Everything appear to work as intended except the send command. Whenever I try to send a command I get an unknown error.

My known list:
`"18:100900":
  class: HGI
"32:162627":
  class: FAN
  _note: SIBER DF EVO4
"37:143839":
  class: REM
  _note: SIBER DF EVO4 Multicontrol DFEVOCTRL08
  commands:
    away: " I --- 37:143839 32:162627--:------ 22F1 003 000107"
    low: " I --- 37:143839 32:162627--:------ 22F1 003 000207"
    medium: " I --- 37:143839 32:162627--:------ 22F1 003 000307"
    high: " I --- 37:143839 32:162627--:------ 22F1 003 000407"
    boost: " I --- 37:143839 32:162627--:------ 22F1 003 000707"
    bypass_off: " W --- 37:143839 32:162627--:------ 22F7 003 00C8EF"
    bypass_on: " W --- 37:143839 32:162627--:------ 22F7 003 0000EF"
    bypass_auto: " W --- 37:143839 32:162627--:------ 22F7 003 00FFEF"
    calendar_off: " W --- 37:143839 32:162627--:------ 22B0 002 0006"
    calendar_on: " W --- 37:143839 32:162627--:------ 22B0 002 0005"`

And this is the error in the log when I try to send any command:

`Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:245
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 16:22:21 (4 occurrences)
Last logged: 16:29:22

[140114538429696] Unexpected exception
[140114154573104] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2761, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2804, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 996, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1068, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 758, in async_handle_set_fan_mode_service
    await self.async_set_fan_mode(fan_mode)
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 766, in async_set_fan_mode
    await self.hass.async_add_executor_job(self.set_fan_mode, fan_mode)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 762, in set_fan_mode
    raise NotImplementedError
NotImplementedError``

I tried to send the command via the FAN entity and via actions (services), with the same result. I managed to call the learn a command service sucessfully, but when trying to send the command I always get the same error:

`Failed to perform the action climate/set_hvac_mode. unknown error`

or

`Failed to perform the action ramses_cc.send_command. Unknown error`
if sent directly from actions

I run my HA in HAOS installed directly on an Intel NUC.

**Comment by zxdavb** [comment]
The trace log you've provided is not for a `send_command`, it's for a service call (probably via the UI).

This service call is not implemented - a PR would be considered.

You should be able to use a custom command instead - submit another issue if that does not work as expected (you may need to ask for help on the user forums).

**Comment by shagadeli** [comment]
Thanks for your reply.
I did again on the Developer tools > Actions > RAMSES RF: Send a Remote command

I get : `Failed to perform the action ramses_cc.send_command. Unknown error`

Log reports:

`Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/ramses_cc/remote.py:208
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 22:53:30 (6 occurrences)
Last logged: 22:59:28

[139956377497328] Error handling message: Unknown error (unknown_error) PLACE from 85.240.139.214 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/ramses_tx/command.py", line 254, in __init__
    super().__init__(frame)
  File "/usr/local/lib/python3.12/site-packages/ramses_tx/frame.py", line 73, in __init__
    raise exc.PacketInvalid(f"Bad frame: invalid structure: >>>{frame}<<<")
ramses_tx.exceptions.PacketInvalid: Bad frame: invalid structure: >>> I --- 37:143838 32:162627--:------ 22F1 003 000407<<<

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 816, in handle_execute_script
    script_result = await script_obj.async_run(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1801, in async_run
    return await asyncio.shield(create_eager_task(run.async_run()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 464, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 528, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 558, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 764, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/ramses_cc/remote.py", line 208, in async_send_command
    cmd = Command(self._commands[command[0]])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ramses_tx/command.py", line 256, in __init__
    raise exc.CommandInvalid(err.message) from err
ramses_tx.exceptions.CommandInvalid: Bad frame: invalid structure: >>> I --- 37:143838 32:162627--:------ 22F1 003 000407<<<`

Any clue of what might be wrong?
