### ISSUE TITLE
ValueError: Invalid result: 1.12 (0x70) is > 1 in home assistant log

### ISSUE THREAD

**Issue by keesma** [zxdavb/ramses_cc#215]
**Describe the bug**
I found the following error message in home assistant.log:

2024-11-27 09:33:02.910 ERROR (MainThread) [ramses_tx.message]  I --- 21:033281 --:------ 21:033281 3EF0 006 0270000A00FF < Coding error: ValueError(Invalid result: 1.12 (0x70) is > 1)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/ramses_tx/message.py", line 255, in _validate
    result = parse_payload(self)
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ramses_tx/parsers.py", line 2938, in parse_payload
    result = _PAYLOAD_PARSERS.get(msg.code, parser_unknown)(msg._pkt.payload, msg)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ramses_tx/parsers.py", line 2513, in parser_3ef0
    mod_level = hex_to_percent(payload[2:4], high_res=False)  # 00-64 (or FF)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ramses_tx/helpers.py", line 337, in hex_to_percent
    raise ValueError(f"Invalid result: {result} (0x{value}) is > 1")
ValueError: Invalid result: 1.12 (0x70) is > 1

**To Reproduce**
I did not take any action myself at that time

**Expected behavior**
No error logging expected

**Please complete the following information:**
 - `ramses_cc:` section from **configuration.yaml**, is empty, all config done in home assistant interface
   - using ramses-esp via mqtt
   - 
 - contemporaneous portion of the **home-assistant.log**, see above
 - contemporaneous portion of the **packet.log**

```
2024-11-27T09:32:23.226935 000 RQ --- 18:101704 13:198915 --:------ 3EF1 001 00
2024-11-27T09:32:23.240699 053 RP --- 13:198915 18:101704 --:------ 3EF1 007 0000900090C8FF
2024-11-27T09:32:37.057462 000 RQ --- 18:101704 10:057591 --:------ 3220 005 0000000000
2024-11-27T09:32:37.071979 072 RP --- 10:057591 18:101704 --:------ 3220 005 00C0000300
2024-11-27T09:32:39.434788 088  I 075 37:211831 --:------ 37:211831 31D9 017 0006010020202020202020202020202000
2024-11-27T09:32:40.121268 000 RQ --- 18:101704 10:057591 --:------ 2401 001 00
2024-11-27T09:32:40.141772 072 RP --- 10:057591 18:101704 --:------ 2401 004 0000054A
2024-11-27T09:32:43.191545 000 RQ --- 18:101704 10:057591 --:------ 3220 005 00001B0000
2024-11-27T09:32:43.216662 074 RP --- 10:057591 18:101704 --:------ 3220 005 00401B47AB
2024-11-27T09:32:46.267178 000 RQ --- 18:101704 10:057591 --:------ 3220 005 0080010000
2024-11-27T09:32:46.291596 074 RP --- 10:057591 18:101704 --:------ 3220 005 00C0012DE6
2024-11-27T09:32:49.339409 000 RQ --- 18:101704 10:057591 --:------ 3220 005 00801C0000
2024-11-27T09:32:49.366462 074 RP --- 10:057591 18:101704 --:------ 3220 005 00C01C47AB
2024-11-27T09:32:52.410936 000 RQ --- 18:101704 10:057591 --:------ 3220 005 0080730000
2024-11-27T09:32:52.425799 074 RP --- 10:057591 18:101704 --:------ 3220 005 00B0730000
2024-11-27T09:32:59.413272 073  I --- 10:057591 --:------ 10:057591 1FD4 003 000C97
2024-11-27T09:32:59.477407 000 RQ --- 18:101704 10:057591 --:------ 3EF0 001 00
2024-11-27T09:32:59.496118 073 RP --- 10:057591 18:101704 --:------ 3EF0 009 0000100A00FF032D64
2024-11-27T09:33:02.236093 000 RQ --- 18:101704 01:026398 --:------ 2349 001 00
2024-11-27T09:33:02.254821 099 RP --- 01:026398 18:101704 --:------ 2349 007 00080200FFFFFF
2024-11-27T09:33:02.910436 101  I --- 21:033281 --:------ 21:033281 3EF0 006 0270000A00FF
2024-11-27T09:33:24.359528 000 RQ --- 18:101704 01:026398 --:------ 0418 003 000000
2024-11-27T09:33:24.382154 029 RP --- 01:026398 18:101704 --:------ 0418 022 004000B0060401000000B898A879FFFFFF70001039C9
2024-11-27T09:33:27.738473 000 RQ --- 18:101704 01:026398 --:------ 2349 001 04
2024-11-27T09:33:27.754573 030 RP --- 01:026398 18:101704 --:------ 2349 007 04064000FFFFFF
2024-11-27T09:33:28.970224 000 RQ --- 18:101704 01:026398 --:------ 2349 001 05
2024-11-27T09:33:28.987286 029 RP --- 01:026398 18:101704 --:------ 2349 007 05070800FFFFFF
2024-11-27T09:33:37.266315 000 RQ --- 18:101704 10:057591 --:------ 3220 005 0000000000
2024-11-27T09:33:37.298269 073 RP --- 10:057591 18:101704 --:------ 3220 005 00C0000300
2024-11-27T09:33:40.338183 000 RQ --- 18:101704 10:057591 --:------ 2401 001 00
2024-11-27T09:33:40.357895 073 RP --- 10:057591 18:101704 --:------ 2401 004 0000054A
2024-11-27T09:33:41.870169 000 RQ --- 18:101704 01:026398 --:------ 2349 001 01
2024-11-27T09:33:41.885612 030 RP --- 01:026398 18:101704 --:------ 2349 007 01080200FFFFFF
2024-11-27T09:33:47.963202 089  I --- 37:049156 --:------ 37:049156 31DA 030 00EF007FFF2AEF7FFF7FFF7FFF7FFFF800EF0101000000EFEF7FFF7FFF00
2024-11-27T09:33:54.466517 000 RQ --- 18:101704 01:026398 --:------ 2349 001 03
2024-11-27T09:33:54.484480 030 RP --- 01:026398 18:101704 --:------ 2349 007 03070800FFFFFF
2024-11-27T09:33:57.846826 000 RQ --- 18:101704 01:026398 --:------ 2E04 001 FF
2024-11-27T09:33:57.861474 030 RP --- 01:026398 18:101704 --:------ 2E04 008 00FFFFFFFFFFFF00
2024-11-27T09:33:59.690725 000 RQ --- 18:101704 10:057591 --:------ 3EF0 001 00
2024-11-27T09:33:59.712854 074 RP --- 10:057591 18:101704 --:------ 3EF0 009 0000100A00FF032D64
2024-11-27T09:34:06.014629 090  I --- 21:033281 --:------ 21:033281 30C9 003 0007A5
2024-11-27T09:34:07.981793 000 RQ --- 18:101704 01:026398 --:------ 0006 001 00
2024-11-27T09:34:07.994690 030 RP --- 01:026398 18:101704 --:------ 0006 004 00050004
2024-11-27T09:34:33.175743 087  I 194 37:049156 --:------ 37:049156 31D9 017 0006010020202020202020202020202000
2024-11-27T09:34:37.475166 000 RQ --- 18:101704 10:057591 --:------ 3220 005 0000000000
2024-11-27T09:34:37.492597 073 RP --- 10:057591 18:101704 --:------ 3220 005 00C0000300
2024-11-27T09:34:40.544688 000 RQ --- 18:101704 10:057591 --:------ 2401 001 00
2024-11-27T09:34:40.571359 073 RP --- 10:057591 18:101704 --:------ 2401 004 0000054A
2024-11-27T09:34:42.173267 081  I --- 37:211856 --:------ 37:211856 31DA 030 00EF007FFF30EF7FFF7FFF7FFF7FFFF800EF0101000000EFEF7FFF7FFF00
2024-11-27T09:34:46.726117 056  I --- 13:198915 --:------ 13:198915 3EF0 003 0000FF
2024-11-27T09:34:46.791604 000 RQ --- 18:101704 13:198915 --:------ 3EF1 001 00
2024-11-27T09:34:46.833108 055 RP --- 13:198915 18:101704 --:------ 3EF1 007 0004B002F400FF
2024-11-27T09:34:48.404947 029  I --- 01:026398 --:------ 01:026398 3B00 002 FCC8
2024-11-27T09:34:48.727216 055  I --- 13:198915 --:------ 13:198915 3EF0 003 0000FF
2024-11-27T09:34:48.853761 000 RQ --- 18:101704 13:198915 --:------ 3EF1 001 00
2024-11-27T09:34:48.895155 055 RP --- 13:198915 18:101704 --:------ 3EF1 007 0004B002F400FF
2024-11-27T09:34:49.727396 055  I --- 13:198915 --:------ 13:198915 3EF0 003 0000FF
2024-11-27T09:34:49.855225 000 RQ --- 18:101704 13:198915 --:------ 3EF1 001 00
2024-11-27T09:34:49.895588 055 RP --- 13:198915 18:101704 --:------ 3EF1 007 0004AF02F300FF
2024-11-27T09:34:59.901794 000 RQ --- 18:101704 10:057591 --:------ 3EF0 001 00
2024-11-27T09:34:59.927240 074 RP --- 10:057591 18:101704 --:------ 3EF0 009 0000100A00FF032D64
```

- Configuration (I removed the devices 37:xxxxx" because they are probably not mine

Evohome with 5 TRV, DTS92 temp sensor, 1 BDR to control floor heating pump and and R8810A (OT) to control central heating

```
"01:022087":
  alias: Controller unknown
"01:026398":
  alias: Controller
"01:145038": {}
"04:014773":
  alias: Natasja
"04:014793":
  alias: Chris
"04:145139":
  alias: Slaapkamer
"04:145159":
  alias: Alex
"04:145175":
  alias: Werkkamer
"05:197404":
  alias: Woonkamer
"10:057591":
  alias: Opentherm
"13:198915":
  alias: Zone valve
"18:101704":
  class: HGI
"21:033281": {}
"22:197404": {}

```

**Screenshots**
n/a

**Additional context**
Add any other context about the problem here, such as the make/model of your hardware.

**Comment by zxdavb** [comment]
This is because some systems use a range `0x00` to `0x64` (0-100 dec), whilst others use `0x00` to `0xC8` (0-200 dec), which is converted to 0.0% to 100.0% (with a possible resolution of 0.5%).

One day, I am going to convert all the existing 0-100 fields to 0-200s, and that will make this go away.

However, there are some rare cases of `0xC9` / `0xCA` !!

**Comment by zxdavb** [comment]
See: https://github.com/zxdavb/ramses_rf/commit/e85910f4bb77680e8d04692563b8a5299ca052a9

Will be in **ramses_rf** _after_ 0.50.0
