### ISSUE TITLE
HA 2024.12.0 fails: AttributeError: module 'logging' has no attribute '_acquireLock'

### ISSUE THREAD

**Issue by remyderuysscher** [zxdavb/ramses_cc#216]
When upgrading to HA 2024.12.0 ramses_cc won't start anymore.

```
Logger: homeassistant.setup
Bron: setup.py:334
Eerst voorgekomen: 07:42:36 (1 gebeurtenissen)
Laatst gelogd: 07:42:36

Setup failed for custom integration 'ramses_cc': Unable to import component: Exception importing custom_components.ramses_cc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/ramses_cc/__init__.py", line 26, in <module>
    from ramses_rf.entity_base import Entity as RamsesRFEntity
  File "/usr/local/lib/python3.13/site-packages/ramses_rf/__init__.py", line 17, in <module>
    from ramses_tx import Address, Command, Message, Packet  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/ramses_tx/__init__.py", line 39, in <module>
    from .gateway import Engine
  File "/usr/local/lib/python3.13/site-packages/ramses_tx/gateway.py", line 31, in <module>
    from .message import Message
  File "/usr/local/lib/python3.13/site-packages/ramses_tx/message.py", line 16, in <module>
    from .packet import Packet
  File "/usr/local/lib/python3.13/site-packages/ramses_tx/packet.py", line 38, in <module>
    PKT_LOGGER = getLogger(f"{__name__}_log", pkt_log=True)
  File "/usr/local/lib/python3.13/site-packages/ramses_tx/logger.py", line 212, in getLogger
    logging._acquireLock()  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'logging' has no attribute '_acquireLock'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1014, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1085, in _get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.ramses_cc

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/ramses_cc/__init__.py", line 26, in <module>
    from ramses_rf.entity_base import Entity as RamsesRFEntity
  File "/usr/local/lib/python3.13/site-packages/ramses_rf/__init__.py", line 17, in <module>
    from ramses_tx import Address, Command, Message, Packet  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/ramses_tx/__init__.py", line 39, in <module>
    from .gateway import Engine
  File "/usr/local/lib/python3.13/site-packages/ramses_tx/gateway.py", line 31, in <module>
    from .message import Message
  File "/usr/local/lib/python3.13/site-packages/ramses_tx/message.py", line 16, in <module>
    from .packet import Packet
  File "/usr/local/lib/python3.13/site-packages/ramses_tx/packet.py", line 38, in <module>
    PKT_LOGGER = getLogger(f"{__name__}_log", pkt_log=True)
  File "/usr/local/lib/python3.13/site-packages/ramses_tx/logger.py", line 212, in getLogger
    logging._acquireLock()  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'logging' has no attribute '_acquireLock'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1034, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1026, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1085, in _get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.ramses_cc
```

**Comment by remyderuysscher** [comment]
Works after upgrading to ramses_cc 5.0

**Comment by donoghdb** [comment]
Yes agree, mine is back working now. Thanks
