### ISSUE TITLE
Home Assistant reporting Invalid Config on Ramses_CC on lastest version of HA

### ISSUE THREAD

**Issue by JulianGroves** [zxdavb/ramses_cc#221]
After upgrading to latest Home Assistant:
Core 2024.12.1
Supervisor 2024.11.4
Operating System 14.0
Frontend 20241127.6

Ramses_CC not starting and Home Assistant reporting the following in the log files:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/ramses_cc/__init__.py", line 26, in <module>
    from ramses_rf.entity_base import Entity as RamsesRFEntity
  File "/usr/local/lib/python3.13/site-packages/ramses_rf/__init__.py", line 17, in <module>
    from ramses_tx import Address, Command, Message, Packet  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/ramses_tx/__init__.py", line 39, in <module>
    from .gateway import Engine
  File "/usr/local/lib/python3.13/site-packages/ramses_tx/gateway.py", line 31, in <module>
    from .message import Message
  File "/usr/local/lib/python3.13/site-packages/ramses_tx/message.py", line 16, in <module>
    from .packet import Packet
  File "/usr/local/lib/python3.13/site-packages/ramses_tx/packet.py", line 38, in <module>
    PKT_LOGGER = getLogger(f"{__name__}_log", pkt_log=True)
  File "/usr/local/lib/python3.13/site-packages/ramses_tx/logger.py", line 212, in getLogger
    logging._acquireLock()  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'logging' has no attribute '_acquireLock'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1014, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1085, in _get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.ramses_cc

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/ramses_cc/__init__.py", line 26, in <module>
    from ramses_rf.entity_base import Entity as RamsesRFEntity
  File "/usr/local/lib/python3.13/site-packages/ramses_rf/__init__.py", line 17, in <module>
    from ramses_tx import Address, Command, Message, Packet  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/ramses_tx/__init__.py", line 39, in <module>
    from .gateway import Engine
  File "/usr/local/lib/python3.13/site-packages/ramses_tx/gateway.py", line 31, in <module>
    from .message import Message
  File "/usr/local/lib/python3.13/site-packages/ramses_tx/message.py", line 16, in <module>
    from .packet import Packet
  File "/usr/local/lib/python3.13/site-packages/ramses_tx/packet.py", line 38, in <module>
    PKT_LOGGER = getLogger(f"{__name__}_log", pkt_log=True)
  File "/usr/local/lib/python3.13/site-packages/ramses_tx/logger.py", line 212, in getLogger
    logging._acquireLock()  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'logging' has no attribute '_acquireLock'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1034, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1026, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1085, in _get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.ramses_cc

**Comment by JulianGroves** [comment]
Extra information:

Logger: homeassistant.components.script
Source: components/script/config.py:147
integration: Scripts ([documentation](https://www.home-assistant.io/integrations/script), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+script%22))
First occurred: 15:14:31 (4 occurrences)
Last logged: 15:14:31

Script with object id 'alias' could not be validated and has been disabled: expected a dictionary. Got 'Evohome Preset Change'
Script with object id 'mode' could not be validated and has been disabled: expected a dictionary. Got 'single'
Script with object id 'icon' could not be validated and has been disabled: expected a dictionary. Got 'mdi:home-thermometer-outline'
Script with object id 'sequence' could not be validated and has been disabled: expected a dictionary. Got [{'service': 'ramses_cc.set_zone_mode', 'data': {'entity_id': '{{ entity_id }}', 'mode': '{{ mode }}', 'setpoint': "{{ state_attr(entity_id, 'temperature') }}"}}]

**Comment by JulianGroves** [comment]
Even more information:

Logger: homeassistant.util.loop
Source: util/loop.py:77
First occurred: 15:14:37 (1 occurrences)
Last logged: 15:14:37

Detected blocking call to import_module with args ('custom_components.ramses_cc',) in /usr/src/homeassistant/homeassistant/loader.py, line 1074: ComponentProtocol, importlib.import_module(self.pkg_path) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.13/asyncio/base_events.py", line 708, in run_until_complete self.run_forever() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 679, in run_forever self._run_once() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2027, in _run_once handle._run() File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component component = await integration.async_get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1026, in async_get_component comp = self._get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component ComponentProtocol, importlib.import_module(self.pkg_path)

**Comment by lloyda** [comment]
Have you upgraded to 0.50.0 ?

**Comment by JulianGroves** [comment]
Hi Lloyda,

Thanks, that was the issue.

My HA didn't offer me the upgrade so I had to manually force it to do the upgrade.

All good now.
