### ISSUE TITLE
Cannot set 'preset_mode' to permanent: For temporary_override, setpoint/active cant be None

### ISSUE THREAD

**Issue by jasperb-iot** [zxdavb/ramses_cc#52]
Hi,

I'm having some issues with setting the zones to 'permanent'. When there is nobody home I want to set the temperature to 10°C and preset mode to permanent. I cannot use the climate.turn_off function because several zones need to remain on.

It doesn't work from the UI (via the thermostat card) and doesn't work in automations. 

Is this a known issue?

![image](https://user-images.githubusercontent.com/107765045/195990312-fa4de43e-511d-4e63-9380-330d331833b1.png)

```text
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/ramses_cc/__init__.py:190
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 13:04:16 (17 occurrences)
Last logged: 15:49:57

[281472772568784] Invalid args: For temporary_override, setpoint/active cant be None
[281472711079536] Invalid args: For temporary_override, setpoint/active cant be None
[281473355301696] Error handling message: Unknown error (unknown_error)
[281472729897696] Invalid args: For temporary_override, setpoint/active cant be None
[281472647221536] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 202, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1738, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1775, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 207, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 931, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 513, in async_set_preset_mode
    await self.hass.async_add_executor_job(self.set_preset_mode, preset_mode)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ramses_cc/climate_heat.py", line 348, in set_preset_mode
    self.svc_set_zone_mode(mode=ZoneMode.TEMPORARY)
  File "/config/custom_components/ramses_cc/climate_heat.py", line 390, in svc_set_zone_mode
    self._call_client_api(
  File "/config/custom_components/ramses_cc/__init__.py", line 190, in _call_client_api
    func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/ramses_rf/system/zones.py", line 748, in set_mode
    cmd = Command.set_zone_mode(
  File "/usr/local/lib/python3.10/site-packages/ramses_rf/protocol/helpers.py", line 27, in wrapper
    return fnc(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/ramses_rf/protocol/command.py", line 193, in wrapper
    return _wrapper(fcn, cls, ctl_id, zone_idx, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/ramses_rf/protocol/command.py", line 158, in _wrapper
    return fcn(cls, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/ramses_rf/protocol/command.py", line 1083, in set_zone_mode
    mode = _normalise_mode(mode, setpoint, until, duration)
  File "/usr/local/lib/python3.10/site-packages/ramses_rf/protocol/command.py", line 223, in _normalise_mode
    raise ValueError(
ValueError: Invalid args: For temporary_override, setpoint/active cant be None
```

I'm using Ramses CC version 0.21.5

Any ideas?

Regards,
Jasper

**Comment by zxdavb** [comment]
This is a known bug.

**Comment by jasperb-iot** [comment]
> This is a known bug. It is on my to-do list.

Thank you for your prompt reply.

**Comment by zxdavb** [comment]
This bug still exists in **0.22.2**.

**Comment by zxdavb** [comment]
This has been fixed by f11e41e523

The **Permanent Override** (and **Advanced Override**) mode must have a target temperature, unlike most other zone modes (their target temperatures are a function of the scheduled setpoint).

The HA web UI does not provide 'space' for this parameter. Therefore, setting the preset_mode to `permanent` via: 
 - the Lovelace (card) UI will use the latest known target temperature as the setpoint
 - a `set_zone_mode` service call (UI or automation) will require an explicit setpoint

**Comment by zxdavb** [comment]
I have changed the title, as that is the error message people will continue to get under some circumstances.

**Comment by jasperb-iot** [comment]
Hi,

This is perfect. Thank you very much.

Regards,
Jasper
