### ISSUE TITLE
0.30.0 - for I|FAN|31D9 - AssertionError: What!! (AA)

### ISSUE THREAD

**Issue by zxdavb** [zxdavb/ramses_cc#77]
```
I 183 32:131922 --:------ 32:131922 31D9 017 0104040020202020202020202020202004 < AssertionError(What!! (AA))
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/ramses_tx/message.py", line 270, in _validate
    return {**self._idx, **result}
              ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ramses_tx/message.py", line 196, in _idx
    assert self._pkt._idx == "00", "What!! (AA)"
           ^^^^^^^^^^^^^^^^^^^^^^
AssertionError: What!! (AA)
```

This idx should be accepted.

**Comment by zxdavb** [comment]
Fixed by commit 9d0d787c
