### ISSUE TITLE
No response for task: throttling to 1/6h

### ISSUE THREAD

**Issue by zxdavb** [zxdavb/ramses_cc#81]
[quote="cmseasy, post:3662, topic:151584"]
`No response for task(2210|RP|32:123456): throttling to 1/6h`
[/quote]

This is not really an error - it is warning you that the `FAN` didn't supply an answer to this `RQ`.

Some ventilations units will, most will not.

It is logspam, really and will be removed at some future stage.

**Comment by zxdavb** [comment]
Starting up Home Assistant Core with ramses 0.30.2 I stll have some warnings and one error:

```
Logger: ramses_rf.entity_base
Source: runner.py:188
First occurred: 15:24:14 (3 occurrences)
Last logged: 15:24:29

No response for task(2210|RP|32:139773): throttling to 1/6h
No response for task(22F8|RP|32:139773): throttling to 1/6h
No response for task(313E|RP|32:139773): throttling to 1/6h
```
I don’t know what this means.
32:139773 is my Orcon HRC425

```
Logger: ramses_tx.message
Source: /usr/local/lib/python3.11/site-packages/ramses_tx/message.py:280
First occurred: 15:23:14 (3 occurrences)
Last logged: 15:24:14

RP --- 32:139773 18:072982 --:------ 2210 042 00FF00FFFFFF0000000000FFFFFFFFFF00FFFFFF0000000000FFFFFFFFFFFFFFFF000000000000020800 < AssertionError(Support the development of ramses_rf by reporting this packet)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/ramses_tx/message.py", line 261, in _validate
    result = PAYLOAD_PARSERS.get(self.code, parser_unknown)(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ramses_tx/parsers.py", line 173, in wrapper
    result = fnc(payload, msg, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ramses_tx/parsers.py", line 1350, in parser_2210
    assert payload in (
           ^^^^^^^^^^^^
AssertionError: Support the development of ramses_rf by reporting this packet
```

**Comment by zxdavb** [comment]
Hmmm - seems the system is not recognizing the RP, just because its payload can't be parsed...

However, this isn't a reason to says that the RQ never got an RP!

It is time to replace the AssertionError with a bespoke Exception.
